#!/usr/bin/env python3
"""
make_testcapture.py - synthesise a fake PulseView CSV capture.

Lets decode_spi.py be exercised without hardware: generates a plausible
UC8179-style three-colour refresh (reset, init, two frame planes, refresh,
long BUSY hold) and writes it in the same CSV shape PulseView exports.

    python3 make_testcapture.py /tmp/fake.csv
    python3 decode_spi.py /tmp/fake.csv

This is a TEST FIXTURE. It proves the decoder works - it proves nothing
whatsoever about the real panel.
"""

from __future__ import annotations

import sys

import numpy as np

SAMPLE_RATE = 20_000_000
SPI_CLOCK = 2_000_000
WIDTH, HEIGHT = 800, 480
PLANE_BYTES = WIDTH * HEIGHT // 8

# (command, payload) - a reduced but realistic UC8179 init
SEQUENCE: list[tuple[int, list[int] | str]] = [
    (0x01, [0x07, 0x07, 0x3F, 0x3F]),   # PWR
    (0x04, []),                          # PON
    (0x00, [0x0F, 0x29]),                # PSR
    (0x61, [0x03, 0x20, 0x01, 0xE0]),    # TRES  800 x 480
    (0x15, [0x00]),
    (0x50, [0x11, 0x07]),                # CDI
    (0x60, [0x22]),                      # TCON
    (0x10, "FRAME"),                     # B/W plane
    (0x13, "FRAME"),                     # RED plane
    (0x12, []),                          # DRF
]


def main() -> int:
    out = sys.argv[1] if len(sys.argv) > 1 else "/tmp/fake_capture.csv"
    spc = SAMPLE_RATE // SPI_CLOCK          # samples per SPI clock period
    half = spc // 2

    sck: list[int] = []
    mosi: list[int] = []
    cs: list[int] = []
    dc: list[int] = []
    busy: list[int] = []
    rst: list[int] = []

    def idle(n: int, busy_level: int = 1, rst_level: int = 1) -> None:
        sck.extend([0] * n)
        mosi.extend([0] * n)
        cs.extend([1] * n)
        dc.extend([1] * n)
        busy.extend([busy_level] * n)
        rst.extend([rst_level] * n)

    def shift(byte: int, dc_level: int) -> None:
        for bit in range(7, -1, -1):
            v = (byte >> bit) & 1
            sck.extend([0] * half + [1] * (spc - half))
            mosi.extend([v] * spc)
            cs.extend([0] * spc)
            dc.extend([dc_level] * spc)
            busy.extend([1] * spc)
            rst.extend([1] * spc)

    # --- reset pulse -----------------------------------------------------
    idle(2000)
    idle(400, rst_level=0)
    idle(2000)

    rng = np.random.default_rng(0xE1)

    for cmd, payload in SEQUENCE:
        idle(40)
        shift(cmd, 0)
        if payload == "FRAME":
            # keep the fixture small: 1/20th of a real plane, still large
            # enough to land in the ">= 1024 bytes" frame-block bucket
            data = rng.integers(0, 256, PLANE_BYTES // 20, dtype=np.uint8)
            for b in data:
                shift(int(b), 1)
        else:
            for b in payload:          # type: ignore[union-attr]
                shift(b, 1)
        idle(40)

    # --- long BUSY hold after DRF ---------------------------------------
    idle(int(SAMPLE_RATE * 0.5), busy_level=0)
    idle(2000)

    n = len(sck)
    arr = np.column_stack([
        np.arange(n, dtype=np.int64),
        np.array(sck, dtype=np.uint8),
        np.array(mosi, dtype=np.uint8),
        np.array(cs, dtype=np.uint8),
        np.array(dc, dtype=np.uint8),
        np.array(busy, dtype=np.uint8),
        np.array(rst, dtype=np.uint8),
    ])

    with open(out, "w") as fh:
        fh.write("; Sample data in CSV format\n")
        fh.write("; Generated by: make_testcapture.py (SYNTHETIC - not real hardware)\n")
        fh.write(f"; Sample rate: {SAMPLE_RATE} Hz\n")
        fh.write(";\n")
        fh.write("Sample,D0,D1,D2,D3,D4,D5\n")
        np.savetxt(fh, arr, fmt="%d", delimiter=",")

    print(f"wrote {out}  ({n:,} samples, {n / SAMPLE_RATE:.3f} s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
